version: '3'
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NEW_NAME: ${DB_NAME}
    depends_on:
      - db
    ports:
      - "${APP_PORT}:3000"
    networks:
      - mynetwork

volumes:
  db-data:

networks:
  mynetwork:
